//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptm_sayonara
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string PaymentType { get; set; }
        public decimal Totalharga { get; set; }
        public string Statuspayments { get; set; }
        public string BookingID { get; set; }
        public string PaymentsID { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Booking Booking1 { get; set; }
        public virtual Booking Booking2 { get; set; }
    }
}
